import type { PqrsRecord } from './types';

export const mockPqrs: PqrsRecord[] = [
  {
    id: '1',
    ticket: 'PQ-2026-00031',
    citizenName: 'Laura Perez',
    subject: 'Retraso en respuesta de peticion',
    description:
      'Se radico una peticion hace mas de 20 dias habiles y no hemos recibido respuesta oficial.',
    directedTo: 'Secretaria General',
    status: 'En revision',
    priority: 'Alta',
    createdAt: '2026-03-18T09:10:00.000Z',
    lastResponseAt: '2026-03-25T15:30:00.000Z',
  },
  {
    id: '2',
    ticket: 'PQ-2026-00042',
    citizenName: 'Daniel Gomez',
    subject: 'Queja por atencion telefonica',
    description: 'Se solicita revisar el trato y tiempos de atencion en la linea de servicio.',
    directedTo: 'Atencion al Ciudadano',
    status: 'Radicada',
    priority: 'Media',
    createdAt: '2026-03-10T11:45:00.000Z',
  },
  {
    id: '3',
    ticket: 'PQ-2026-00019',
    citizenName: 'Maria Restrepo',
    subject: 'Solicitud de copia de respuesta previa',
    description: 'Requiero copia del oficio enviado en diciembre para adjuntarlo a tramite nuevo.',
    directedTo: 'Archivo Central',
    status: 'Respondida',
    priority: 'Baja',
    createdAt: '2026-02-28T08:20:00.000Z',
    lastResponseAt: '2026-03-04T14:05:00.000Z',
  },
  {
    id: '4',
    ticket: 'PQ-2026-00027',
    citizenName: 'Andres Giraldo',
    subject: 'Peticion de informacion de contrato',
    description: 'Solicitamos informacion publica sobre el estado de ejecucion del contrato 871.',
    directedTo: 'Secretaria de Hacienda',
    status: 'En revision',
    priority: 'Alta',
    createdAt: '2026-03-02T16:00:00.000Z',
    lastResponseAt: '2026-03-08T09:10:00.000Z',
  },
];
