from __future__ import annotations

from typing import Protocol


class PqrsdRepository(Protocol):
    async def insert_request(self, record: dict) -> None: ...

    async def fetch_latest_request(self) -> dict | None: ...

    async def fetch_requests(self, limit: int = 100) -> list[dict]: ...

    async def fetch_request_by_id(self, request_id: str) -> dict | None: ...

    async def patch_request(self, request_id: str, updates: dict) -> dict | None: ...
